/**
 * Testi dell'interfaccia del corso di italiano (per chi parla portoghese europeo).
 * Lo specchio del corso portoghese: pulsanti ed etichette brevi in italiano (immersione),
 * spiegazioni e istruzioni in portoghese europeo (la lingua di chi impara).
 * Le chiavi sono le stesse di courses/pt/ui.ts: il tipo UiStrings lo controlla.
 */
import type { UiStrings } from '../../course-config';

export const ui: UiStrings = {
  /** Parole ricorrenti */
  common: {
    start: 'Inizia',
    continue: 'Continua',
    soon: 'Presto',
    listen: 'Ascolta',
    listenSlow: 'Ascolta piano',
    close: 'Chiudi',
    send: 'Invia',
    sending: 'Invio…',
    cancel: 'Annulla',
    retry: 'Tenta de novo',
    offline: 'Senza connessione',
    back: 'Indietro',
    check: 'Verifica',
  },
  mascot: 'Galo, la mascotte',
  nav: { path: 'Percorso' },
  header: { streak: 'Giorni di fila', xpToday: 'XP de hoje / objetivo' },
  audio: { on: 'Attiva il suono', off: 'Disattiva il suono', pronunciation: 'Ascolta la pronuncia' },
  learnerNote: { title: 'Para quem fala português', short: 'Nota para portugueses' },
  grammar: {
    title: 'Grammatica',
    subtitle: 'O caderno do que estudaste no percurso.',
    empty: 'Aqui vais encontrar os verbos à medida que os estudas. O primeiro chega em breve no percurso!',
    verbs: 'Verbi',
    tense: 'Tempo verbale',
    studyStepByStep: '📖 Ripassa passo passo',
    practice: '✏️ Allenati',
    search: 'Procura um verbo ou uma forma',
    searchPlaceholder: 'ex. eravamo, noi siamo, stare',
    clearSearch: 'Apagar a pesquisa',
    allTenses: 'Tutti',
    noResults: (q: string) => `Nenhum verbo com «${q}» entre os que estudaste.`,
    preview: 'Anteprima',
    previewNote: 'Ainda não encontraste este tempo no percurso.',
  },
  /** Tab Ascolto: registrazioni vere */
  listen: {
    title: 'Ascolto',
    subtitle: 'Italiano gravado por uma pessoa de verdade, a falar normalmente.',
    tip: 'Ouve primeiro sem texto: quantas palavras reconheces? Depois abre o texto e ouve outra vez.',
    play: 'Riproduci',
    pause: 'Pausa',
    back5: 'Indietro di 5 secondi',
    slow: 'Più piano',
    position: 'Posizione nella registrazione',
    showText: 'Mostra il testo',
    hideText: 'Nascondi il testo',
    showTranslation: 'Tradução',
    hideTranslation: 'Sem tradução',
    error: 'Não foi possível carregar o áudio. Verifica a ligação e tenta de novo.',
  },
  /** Sessione Ascolto dei nodi conversazione */
  listening: {
    title: 'Ascolta la conversazione',
    hint: 'Ainda sem texto: tenta perceber o essencial. Podes ouvir as vezes que quiseres.',
    play: 'Ascolta',
    replay: 'Riascolta',
    stop: 'Pausa',
    listenFirst: 'Ouve primeiro a conversa toda',
    toQuestions: 'Alle domande',
    question: (i: number, n: number) => `Domanda ${i} di ${n}`,
    correct: 'Esatto!',
    rightAnswer: (a: string) => `Era: ${a}`,
    transcript: 'La conversazione',
    transcriptHint: 'Agora com o texto. Toca numa frase para a ouvir outra vez.',
    line: (i: number) => `Frase ${i}`,
  },
  /** Punti difficili (tab della Grammatica) */
  skills: {
    title: 'Punti difficili',
    intro: 'O que costuma custar a quem fala português. Em cima, aquilo em que erras mais.',
    errors: (n: number) => `${n} ${n === 1 ? 'erro' : 'erros'}`,
    fresh: 'Ainda não treinado',
    noErrors: 'Sem erros até agora',
    due: 'Para rever',
    practice: (n: number) => `✏️ Allenati (${n})`,
  },
  review: {
    title: 'Ripasso',
    due: (n: number) => `${n} ${n === 1 ? 'coisa para rever' : 'coisas para rever'}`,
    allDone: 'Tudo revisto: podes treinar na mesma',
    empty: 'Ainda não há nada para rever: faz primeiro algumas sessões.',
    done: 'Ripasso completato',
    doneNote: 'As expressões que erraste voltam em breve, as que acertaste mais tarde.',
  },
  complete: {
    done: 'Sessione completata!',
    perfect: 'Nessun errore!',
    keepGoing: 'Completata, continua così!',
    accuracy: 'Precisione',
    combo: 'Di fila',
    days: 'Giorni',
  },
  testFailed: {
    title: 'Quasi!',
    body: (accuracy: number, needed: number) => `Acertaste ${accuracy}% à primeira. Para passar o teste precisas de ${needed}%.`,
    hint: 'Se quiseres, repete primeiro a sessão “Produzione”: é o melhor treino para o teste.',
  },
  trace: {
    accents: 'Quase! Confere os acentos.',
    otherExpression: (form: string) => `«${form}» existe, mas aqui há uma expressão mais adequada.`,
    notYet: 'Ainda não. Tenta outra vez ou carrega em “Non lo so”.',
    writeForm: (form: string) => `scrivi ${form}`,
    writeAnswer: 'scrivi la risposta',
    accentLetters: 'Lettere accentate',
    missingAccent: (c: string) => `Manca l’accento: ${c}`,
  },
  vocabStudy: {
    traceHint: 'Ouve e escreve por cima do modelo.',
    inTarget: 'In italiano',
    recallHint: 'O que dizes em cada situação? Os erros aqui não contam.',
  },
  feedback: {
    thanks: 'Grazie!',
    received: 'Recebemos: ajuda-nos mesmo a melhorar a app.',
    offline: 'Senza connessione: tenta de novo quando voltar a rede.',
    error: 'Não conseguimos enviar.',
    or: 'ou',
    writeEmail: 'escreve-nos um email',
    generalSubtitle: 'O que gostas, o que falta, o que não funciona: tudo é útil.',
    message: 'A tua mensagem',
    email: 'O teu email (opcional)',
    emailHint: 'Só se quiseres uma resposta. Usamo-lo apenas para te responder.',
    emailInvalid: 'Confirma o endereço de email.',
    mailKeepLines: 'Não apagues estas linhas: ajudam-nos a perceber de que falas.',
  },
  report: {
    title: 'Qual é o problema?',
    subtitle: 'Escolhe o que descreve melhor o que está mal.',
    reason: 'Motivo',
    reasons: {
      not_accepted: 'A minha resposta estava certa, mas não foi aceite',
      portuguese: 'Há um erro no italiano',
      translation: 'Tradução ou explicação errada',
      audio: 'O áudio não funciona ou diz outra coisa',
      unclear: 'O exercício não é claro',
      other: 'Outro',
    },
    noteRequired: 'Conta-nos o que está mal',
    noteOptional: 'Queres acrescentar alguma coisa? (opcional)',
    notAcceptedExample: 'Ex.: escrevi «Ciao» e devia estar certo',
    includes: 'Enviamos também o exercício, a tua resposta e a versão da app, para o encontrarmos logo.',
  },
  map: {
    skipToTest: '⏩ Salta al test',
    skipHint: 'Já sabes isto? Com 80% no teste a lição fica feita.',
    chapter: (n: number) => `Capitolo ${n}`,
    lessonsDone: (done: number, total: number) => `${done} di ${total} lezioni fatte`,
    completed: 'completata',
    soon: 'presto',
    locked: 'bloccata',
    sessionsDone: (done: number, total: number) => `${done} di ${total} sessioni`,
    draftHint: 'Presto: esta lição está a ser preparada.',
    lockedHint: 'Completa as lições anteriores para desbloquear.',
    sessions: 'Sessioni',
    sessionDoneRepeat: 'fatta, toca para repetir',
    repeat: 'Ripeti',
  },
  menu: {
    open: 'Apri il menu',
    close: 'Chiudi il menu',
    sound: 'Suono',
    save: 'Salva i progressi',
    saveHint: 'Com o Google encontras o teu progresso noutro telemóvel',
    saveError: 'Não correu bem: tenta daqui a pouco',
    opening: 'Apro Google…',
    googleAccount: 'Account Google',
    safe: 'Progresso guardado',
    feedback: 'Invia un feedback',
    feedbackHint: 'Diz-nos o que achas',
    privacy: 'Privacy',
    deleteAccount: 'Elimina l’account',
    deleteAccountHint: 'Apaga a conta e o progresso',
    version: 'versione',
    sync: {
      connecting: 'A ligar à nuvem…',
      pending: 'A guardar na nuvem…',
      synced: 'Progresso guardado na nuvem',
      offline: 'Offline: progresso guardado no telemóvel',
      error: 'Nuvem inacessível: progresso guardado no telemóvel',
    },
  },
  deleteAccount: {
    title: 'Eliminare l’account?',
    body: 'Apagamos a tua conta e todo o progresso: lições feitas, XP, dias seguidos e revisões, tanto na nuvem como neste dispositivo.',
    warning: 'Não se pode desfazer: vais recomeçar do início.',
    offline: 'Senza connessione: é preciso rede para apagar os dados na nuvem.',
    error: 'Não conseguimos. Tenta daqui a pouco.',
    deleting: 'Elimino…',
    confirm: 'Elimina tutto',
  },
  lesson: {
    listenTo: (text: string) => `Ascolta «${text}»`,
    loading: 'Carico la lezione',
    notSaved: 'Esta lição ainda não está guardada no telemóvel. Abre-a quando voltar a rede.',
    notFound: 'Lezione non trovata',
    backToMap: 'Torna al percorso',
    upNext: 'A seguir',
    nextUnlocked: 'A próxima lição já está desbloqueada!',
    lessonDone: 'Lezione completata! A próxima já está desbloqueada.',
    finish: 'Fine',
    theoryFirst: 'Prima, un po’ di teoria!',
    examples: 'Esempi',
    listenSentence: 'Ascolta la frase',
    exit: 'Esci dalla lezione',
    noExercises: 'Qui non ci sono ancora esercizi',
  },
  dialogue: {
    defaultSpeaker: 'Cameriere',
    empty: 'Qui non c’è ancora una conversazione',
    emptyHint: 'Esta lição está a ser preparada.',
    typing: 'sta scrivendo…',
    today: 'Oggi',
    online: 'online',
    showTranslation: 'Ver tradução',
    hideTranslation: 'Esconder tradução',
    possibleAnswers: 'Risposte possibili',
  },
  /** Campo di risposta ed esito */
  answer: {
    yourAnswer: 'La tua risposta',
    placeholder: 'Scrivi la parola che manca',
    specialChars: 'Caratteri speciali',
    accentHint: 'Quase! Confere os acentos',
    doublesNote: (answer: string) => `Atenção às consoantes duplas: escreve-se «${answer}». Em italiano a dupla ouve-se, é mais longa, e muda o sentido (caro/carro).`,
    dontKnow: 'Non lo so',
    listenAndWrite: 'Ascolta e scrivi',
    writeInTarget: 'Scrivi in italiano',
    listenAndChoose: 'Ascolta e scegli',
    options: 'Opzioni',
    listenAgain: 'Ascolta di nuovo',
  },
  feedbackSheet: {
    praise: ['Molto bene!', 'Bravissima!', 'Perfetto!', 'Ottimo!', 'Esatto!'],
    report: 'Segnala un problema in questo esercizio',
    reportHint: 'Reportar um problema neste exercício',
    reportShort: 'Segnala',
    tapCorrect: 'Tocca la risposta giusta',
    comboLabel: (n: number) => `${n} risposte giuste di fila`,
    combo: (n: number) => `${n} di fila!`,
    correctIs: (answer: string) => `La risposta giusta è “${answer}”`,
    notYet: 'Non ancora',
    showSolution: 'Vedi la soluzione',
    tryAgain: 'Riprova',
  },
  onboarding: {
    step: (n: number, total: number) => `Passo ${n} de ${total}`,
    welcomeTitle: 'Ciao! Io sono il Galo.',
    /** Testo di benvenuto: [prima, parte in grassetto, dopo] */
    welcomeBody: ['Acompanho-te no ', 'italiano', ', a língua de Roma, Florença e Milão, explicado para quem fala português.'],
    welcomeNote: 'Poucas expressões de cada vez, logo postas em prática.',
    letsGo: 'Andiamo!',
    motivationTitle: 'Porque aprendes italiano?',
    motivations: {
      viaggio: 'Uma viagem a Itália',
      trasferimento: 'Vou viver ou trabalhar lá',
      persone: 'Amigos, família, namorado',
      curiosita: 'Curiosidade, gosto da língua',
    },
    goalTitle: 'Quanto queres estudar por dia?',
    goalSubtitle: 'Basta uma sessão por dia para manter a sequência.',
    goals: {
      light: { label: 'Leve', detail: 'cerca de 2 sessões, 5 minutos por dia' },
      regular: { label: 'Regular', detail: 'cerca de 3 sessões, 10 minutos por dia' },
      intense: { label: 'Intenso', detail: 'cerca de 5 sessões, 15–20 minutos por dia' },
    },
    audioTitle: 'Experimenta o áudio',
    audioBody: 'Vais ouvir muitas frases: confirma que o som está ligado.',
    audioSample: 'Ciao! Benvenuta in Italia.',
    audioOk: 'Ouço bem: iniziamo!',
    audioLater: 'Agora não posso ouvir',
  },
  /** Categorie dei nodi sulla mappa */
  kinds: {
    verb: 'Verbo',
    vocab: 'Vocabolario',
    dialogue: 'Conversazione',
    culture: 'Cultura · facoltativo',
    checkpoint: 'Sfida',
  },
  /** Titolo di un nodo verbo, es. "Verbo essere" */
  verbNodeTitle: (title: string) => `Verbo ${title}`,
  exercise: {
    conjugate: (infinitive: string, tense: string) => `Coniuga il verbo ${infinitive} (${tense})`,
    complete: 'Completa la frase',
    choose: 'Scegli l’opzione giusta',
    verbDrill: (infinitive: string, tense: string) => `Verbo ${infinitive} · ${tense}`,
  },
  paradigm: {
    singular: 'Singolare',
    plural: 'Plurale',
    all: 'Tutte le forme',
    recall: 'Ora a memoria',
    traceHint: 'Escreve cada forma por cima do modelo.',
    recallHint: 'Escreve as formas sem modelo. Os erros aqui não contam.',
  },
  sessions: {
    discovery: { name: 'Scoperta', description: 'Teoria, ouvir e copiar' },
    guided: { name: 'Pratica', description: 'Exercícios com opções e ajudas' },
    listening: { name: 'Ascolto', description: 'Ouve a conversa, ainda sem texto' },
    production: { name: 'Produzione', description: 'Escreve tudo sozinha, sem opções' },
    test: { name: 'Test finale', description: 'Tudo misturado: precisas de 80% para passar' },
    newExpressions: 'novas expressões',
    learnPart: (what: string) => `Aprende: ${what}`,
    practicePart: (what: string) => `Pratica: ${what}`,
    practicePartWithReview: (what: string) => `Pratica: ${what}, e uma revisão`,
    verbDiscovery: 'A regra e as suas formas, para ouvir e copiar',
    dialogueDiscovery: 'As frases de que precisas na conversa',
    cultureDiscovery: 'Uma curiosidade para ler',
    cultureGuided: 'Três perguntas rápidas',
    dialogueGuided: 'A conversa, com opções e ajudas',
    dialogueProduction: 'A conversa, toda para escrever',
    dialogueTest: 'A conversa sem ajudas: precisas de 80%',
    checkpoint: 'Frases de todo o capítulo: precisas de 80%',
  },
};
