/**
 * Testi dell'interfaccia di Falaluso.
 * Due lingue, di proposito: pulsanti ed etichette brevi in portoghese (immersione),
 * spiegazioni e istruzioni in italiano (la lingua di chi impara).
 * Gli altri corsi hanno un file con le stesse chiavi (il tipo PtUi lo controlla).
 */
export const ui = {
  /** Parole ricorrenti */
  common: {
    start: 'Começar',
    continue: 'Continuar',
    soon: 'Em breve',
    listen: 'Ouvir',
    listenSlow: 'Ouvir devagar',
    close: 'Fechar',
    send: 'Enviar',
    sending: 'A enviar…',
    cancel: 'Cancelar',
    retry: 'Riprova',
    offline: 'Sem ligação',
    back: 'Voltar',
  },
  mascot: 'Galo, a mascote',
  nav: { path: 'Percurso' },
  header: { streak: 'Dias seguidos', xpToday: 'XP di oggi / obiettivo' },
  audio: { on: 'Ligar o som', off: 'Desligar o som', pronunciation: 'Ouvir pronúncia' },
  learnerNote: { title: 'Per chi parla italiano', short: 'Nota per italiani' },
  grammar: {
    title: 'Gramática',
    subtitle: 'Il quaderno di quello che hai studiato nel percorso.',
    empty: 'Qui troverai i verbi man mano che li studi. Il primo arriva presto nel percorso!',
    verbs: 'Verbos',
    tense: 'Tempo verbal',
  },
  review: {
    title: 'Revisão',
    due: (n: number) => `${n} ${n === 1 ? 'cosa da rinfrescare' : 'cose da rinfrescare'}`,
    allDone: 'Tutto ripassato: puoi allenarti comunque',
    empty: 'Ancora niente da ripassare: completa prima qualche sessione.',
    done: 'Revisão concluída',
    doneNote: 'Le espressioni sbagliate torneranno presto, quelle giuste più avanti.',
  },
  complete: {
    done: 'Sessão concluída!',
    perfect: 'Sem erros!',
    keepGoing: 'Concluída, continua assim!',
    accuracy: 'Precisão',
    combo: 'Seguidas',
    days: 'Dias',
  },
  testFailed: {
    title: 'Quase lá!',
    body: (accuracy: number, needed: number) => `Acertaste ${accuracy}% à primeira. Para passar o teste precisas de ${needed}%.`,
    hint: 'Se quiseres, repete primeiro a sessão “Produção”: é o melhor treino para o teste.',
  },
  trace: {
    accents: 'Quase! Confere os acentos.',
    otherExpression: (form: string) => `«${form}» existe, mas aqui há uma expressão mais adequada.`,
    notYet: 'Ainda não. Tenta outra vez ou carrega em “Não sei”.',
    writeForm: (form: string) => `escreve ${form}`,
    writeAnswer: 'escreve a resposta',
    accentLetters: 'Letras com acento',
    missingAccent: (c: string) => `Falta o acento: ${c}`,
  },
  vocabStudy: {
    traceHint: 'Ouve e escreve por cima do modelo.',
    inTarget: 'Em português',
    recallHint: 'O que dizes em cada situação? Os erros aqui não contam.',
  },
  feedback: {
    thanks: 'Obrigado!',
    received: 'L’abbiamo ricevuto: ci aiuta davvero a migliorare Falaluso.',
    offline: 'Sem ligação: riprova quando torna la rete.',
    error: 'Non siamo riusciti a inviarlo.',
    or: 'oppure',
    writeEmail: 'scrivici un’email',
    generalSubtitle: 'Cosa ti piace, cosa manca, cosa non funziona: tutto è utile.',
    message: 'Il tuo messaggio',
    email: 'La tua email (facoltativa)',
    emailHint: 'Solo se vuoi una risposta. La usiamo solo per risponderti.',
    emailInvalid: 'Controlla l’indirizzo email.',
    mailKeepLines: 'Non cancellare queste righe: ci aiutano a capire di cosa parli.',
  },
  report: {
    title: 'Qual è il problema?',
    subtitle: 'Scegli quello che descrive meglio cosa non va.',
    reason: 'Motivo',
    reasons: {
      not_accepted: 'La mia risposta era giusta, ma non è stata accettata',
      portuguese: 'C’è un errore nel portoghese',
      translation: 'Traduzione o spiegazione sbagliata',
      audio: 'L’audio non va o dice altro',
      unclear: 'L’esercizio non è chiaro',
      other: 'Altro',
    },
    noteRequired: 'Raccontaci cosa non va',
    noteOptional: 'Vuoi aggiungere qualcosa? (facoltativo)',
    notAcceptedExample: 'Es. ho scritto «Olá» e dovrebbe andare bene',
  },
  map: {
    chapter: (n: number) => `Capítulo ${n}`,
    lessonsDone: (done: number, total: number) => `${done} de ${total} lições feitas`,
    completed: 'concluída',
    soon: 'em breve',
    locked: 'bloqueada',
    sessionsDone: (done: number, total: number) => `${done} de ${total} sessões`,
    draftHint: 'Em breve: esta lição está a ser preparada.',
    lockedHint: 'Completa as lições anteriores para desbloquear.',
    sessions: 'Sessões',
    sessionDoneRepeat: 'feita, toca para repetir',
    repeat: 'Repetir',
  },
  menu: {
    open: 'Abrir o menu',
    close: 'Fechar o menu',
    sound: 'Som',
    save: 'Guardar progresso',
    saveHint: 'Con Google li ritrovi anche su un altro telefono',
    saveError: 'Non è andata: riprova tra poco',
    opening: 'A abrir o Google…',
    googleAccount: 'Conta Google',
    safe: 'Progressi al sicuro',
    feedback: 'Enviar feedback',
    feedbackHint: 'Scrivici cosa ne pensi',
    privacy: 'Privacidade',
    deleteAccount: 'Apagar conta',
    deleteAccountHint: 'Cancella account e progressi',
    version: 'versão',
    sync: {
      connecting: 'Collegamento al cloud…',
      pending: 'Salvataggio nel cloud…',
      synced: 'Progressi salvati nel cloud',
      offline: 'Offline: progressi salvati sul telefono',
      error: 'Cloud non raggiungibile: progressi salvati sul telefono',
    },
  },
  deleteAccount: {
    title: 'Apagar a conta?',
    body: 'Cancelliamo il tuo account e tutti i progressi: lezioni completate, XP, serie di giorni e ripasso, sia nel cloud sia su questo dispositivo.',
    warning: 'Non si può annullare: ripartirai dall’inizio.',
    offline: 'Sem ligação: serve la rete per cancellare i dati nel cloud.',
    error: 'Non ci siamo riusciti. Riprova tra poco, oppure scrivici dalla pagina Privacidade.',
    deleting: 'A apagar…',
    confirm: 'Apagar tudo',
  },
  lesson: {
    listenTo: (text: string) => `Ouvir «${text}»`,
    loading: 'A carregar a lição',
    notSaved: 'Questa lezione non è ancora salvata sul telefono. Aprila quando torna la rete.',
    notFound: 'Não encontrámos esta lição',
    backToMap: 'Voltar ao percurso',
    upNext: 'A seguir',
    nextUnlocked: 'A próxima lição já está desbloqueada!',
    lessonDone: 'Lição concluída! A próxima já está desbloqueada.',
    finish: 'Concluir',
    theoryFirst: 'Primeiro, um pouco de teoria!',
    examples: 'Exemplos',
    listenSentence: 'Ouvir a frase',
    exit: 'Sair da lição',
    noExercises: 'Ainda não há exercícios aqui',
  },
  dialogue: {
    defaultSpeaker: 'Empregado',
    empty: 'Ainda não há conversa aqui',
    emptyHint: 'Esta lição está a ser preparada.',
    typing: 'a escrever…',
    online: 'online',
    showTranslation: 'Ver tradução',
    hideTranslation: 'Esconder tradução',
    possibleAnswers: 'Respostas possíveis',
  },
  /** Campo di risposta ed esito */
  answer: {
    yourAnswer: 'A tua resposta',
    placeholder: 'Escreve a palavra que falta',
    specialChars: 'Caracteres especiais',
    accentHint: 'Quase! Confere os acentos',
    dontKnow: 'Não sei',
    listenAndWrite: 'Ouve e escreve',
    writeInTarget: 'Escreve em português',
    listenAndChoose: 'Ouve e escolhe',
    options: 'Opções',
    listenAgain: 'Ouvir outra vez',
  },
  feedbackSheet: {
    praise: ['Muito bem!', 'Excelente!', 'Perfeito!', 'Boa!', 'Isso mesmo!'],
    report: 'Reportar um problema neste exercício',
    reportHint: 'Segnala un problema in questo esercizio',
    tapCorrect: 'Toca na resposta certa',
    comboLabel: (n: number) => `${n} respostas certas seguidas`,
    combo: (n: number) => `${n} seguidas!`,
    correctIs: (answer: string) => `A resposta certa é “${answer}”`,
    notYet: 'Ainda não',
    showSolution: 'Ver a solução',
    tryAgain: 'Tentar de novo',
  },
  onboarding: {
    step: (n: number, total: number) => `Passo ${n} di ${total}`,
    welcomeTitle: 'Olá! Eu sou o Galo.',
    /** Testo di benvenuto: [prima, parte in grassetto, dopo] */
    welcomeBody: ['Ti accompagno nel ', 'portoghese del Portogallo', ', quello di Lisbona e Porto, spiegato per chi parla italiano.'] as [string, string, string],
    welcomeNote: 'Poche espressioni alla volta, subito in pratica.',
    letsGo: 'Vamos!',
    motivationTitle: 'Perché impari il portoghese?',
    motivations: {
      viaggio: 'Un viaggio in Portogallo',
      trasferimento: 'Mi trasferisco o lavoro lì',
      persone: 'Amici, famiglia, partner',
      curiosita: 'Curiosità, mi piace la lingua',
    },
    goalTitle: 'Quanto vuoi studiare ogni giorno?',
    goalSubtitle: 'Basta una sessione al giorno per tenere viva la streak.',
    goals: {
      light: { label: 'Leggero', detail: 'circa 2 sessioni, 5 minuti al giorno' },
      regular: { label: 'Regolare', detail: 'circa 3 sessioni, 10 minuti al giorno' },
      intense: { label: 'Intenso', detail: 'circa 5 sessioni, 15–20 minuti al giorno' },
    },
    audioTitle: 'Prova l’audio',
    audioBody: 'Ascolterai molte frasi: controlla che il volume sia acceso.',
    audioSample: 'Olá! Bem-vindo a Portugal.',
    audioOk: 'Sento bene: começar!',
    audioLater: 'Non posso ascoltare ora',
  },
  /** Categorie dei nodi sulla mappa */
  kinds: {
    verb: 'Verbo',
    vocab: 'Vocabulário',
    dialogue: 'Conversa',
    culture: 'Cultura · opcional',
    checkpoint: 'Desafio',
  },
  /** Titolo di un nodo verbo, es. "Verbo ser" */
  verbNodeTitle: (title: string) => `Verbo ${title}`,
  exercise: {
    conjugate: (infinitive: string, tense: string) => `Conjuga o verbo ${infinitive} (${tense})`,
    complete: 'Completa a frase',
    choose: 'Escolhe a opção certa',
    verbDrill: (infinitive: string, tense: string) => `Verbo ${infinitive} · ${tense}`,
  },
  paradigm: {
    singular: 'Singular',
    plural: 'Plural',
    all: 'Todas as formas',
    recall: 'Agora de memória',
    traceHint: 'Escreve cada forma por cima do modelo.',
    recallHint: 'Escreve as formas sem modelo. Os erros aqui não contam.',
  },
  sessions: {
    discovery: { name: 'Descoberta', description: 'Teoria, ascolto e ricopiatura' },
    guided: { name: 'Prática', description: 'Esercizi con opzioni e aiuti' },
    listening: { name: 'Escuta', description: 'Ascolta e scrivi' },
    production: { name: 'Produção', description: 'Scrivi tutto da solo, senza opzioni' },
    test: { name: 'Teste final', description: 'Tutto mescolato: serve l’80% per superarlo' },
    newExpressions: 'nuove espressioni',
    learnPart: (what: string) => `Impara: ${what}`,
    practicePart: (what: string) => `Esercitati: ${what}`,
    practicePartWithReview: (what: string) => `Esercitati: ${what}, più un ripasso`,
    verbDiscovery: 'La regola e le sue forme, da ascoltare e ricopiare',
    dialogueDiscovery: 'Le frasi che ti servono nella conversazione',
    cultureDiscovery: 'Una curiosità da leggere',
    cultureGuided: 'Tre domande veloci',
    dialogueGuided: 'La conversazione, con opzioni e aiuti',
    dialogueProduction: 'La conversazione, tutta da scrivere',
    dialogueTest: 'La conversazione senza aiuti: serve l’80%',
    checkpoint: 'Frasi da tutto il capitolo: serve l’80%',
  },
};

export type PtUi = typeof ui;
